version: 2.0

jobs:
    build:
        docker:
            -   image: circleci/php:7.2
        steps:
            - checkout
            -   run: composer install -n --prefer-dist
            -   run: composer test
